<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>

   
        <h3 class="underlineborder" id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign In')) ?></h3>
  
    <div class="col2-set" aria-labelledby="block-customer-login-heading">
    	<div class="registered-users half-box">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="content fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <h3>Already registered</h3>
                <p class="form-instructions"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></p>
                <ul>
                <li>
                    <label class="label" for="email"><?= $block->escapeHtml(__('Email')) ?></label>
                    <div class="input-box">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </li>
                <li>
                    <label for="pass" class="label"><?= $block->escapeHtml(__('Password')) ?></label>
                    <div class="input-box">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </li>
                <?= $block->getChildHtml('form_additional_info') ?>
                <li>
                    
                   <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                </li>
                </ul>
            </div>
            <div class="buttons-set">
                <button type="submit" class="action login button btn" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button>
            </div>
        </form>
    
    </div>
