<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Sharing $block */
?>
<div id="emailme_popup" class="emailme_popup">
    <div class="box">
        <h3> <?= $block->escapeHtmlAttr(__('Email my Saved Items')) ?> </h3>
<form class="form wishlist share"
      action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
      id="form-validate"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    
        <?= $block->getBlockHtml('formkey') ?>
       
        <p>
            <label class="label" for="email_address"><?= $block->escapeHtml(__('Email addresses, separated by commas')) ?></label>
            
                <textarea name="emails" cols="60" rows="5" id="email_address" data-validate="{required:true,'validate-emails':true}"><?= /* @noEscape */ $block->getEnteredData('emails') ?></textarea>
        </p>
        <p>
            <label class="label" for="message"><?= $block->escapeHtml(__('Message')) ?></label>
            <textarea id="message" name="message" cols="60" rows="5"><?= /* @noEscape */ $block->getEnteredData('message') ?></textarea>
        </p>
        <?php /* if ($this->helper('Magento\Wishlist\Helper\Rss')->isRssAllow()): ?>
            <div class="field choice rss">
                <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?= $block->escapeHtmlAttr(__('Check here to link an RSS feed to your Wish List.')) ?>" class="checkbox">
                <label class="label" for="rss_url">
                    <span>
                        <?= $block->escapeHtml(__('Check here to link an RSS feed to your Wish List.')) ?>
                    </span>
                </label>
            </div>
        <?php endif; */ ?>
    
    <p>
        
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Share Wish List')) ?>" class="action submit primary btn">
                <span><?= $block->escapeHtml(__('Share Wish List')) ?></span>
            </button>
        
    </p>
</form>
    </div>
</div>