<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="center_text">
<div class="cart-empty">
	<h1 class="same-title"><?= /* @escapeNotVerified */ __('Gym Bag is empty') ?></h1>
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= /* @escapeNotVerified */ __('You have no items in your shopping cart.') ?></p>
    <p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.',
            $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
</div>
<script>
jQuery(document).ready(function(){
	jQuery(".container-right").remove();
	jQuery(".container-left").css('width','100%');
});
</script>