<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Order Information') ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="col2-set order-info-box">
            <div class="col-1">
                <div class="box">
                    <div class="box-title"><?= /* @escapeNotVerified */ __('Shipping Address') ?></div>
                    <div class="box-content">
                        <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                    </div>
                </div>
            </div>

            <div class="col-2">
                <div class="box">
                    <div class="box-title"><?= /* @escapeNotVerified */ __('Shipping Method') ?></div>
                    <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?= /* @escapeNotVerified */ __('No shipping information available') ?>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
        <div class="col2-set order-info-box">
            <div class="col-1">
            <div class="box">
                <div class="box-title"><?= /* @escapeNotVerified */ __('Billing Address') ?></div>
                <div class="box-content">
                    <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
                </div>
            </div>
            </div>
            <div class="col-2">
            <div class="box">
                <div class="box-title"><?= /* @escapeNotVerified */ __('Payment Method') ?></div>
                <div class="box-content">
                    <?= $block->getPaymentInfoHtml() ?>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<script>
    var ord_no = jQuery(".black-box h3 span").text();
    var ord_status = jQuery(".page-title.title-buttons .order-status").text();
    jQuery(".page-title.title-buttons .order-status").text(ord_no+' - '+ord_status);
    jQuery( ".page-title.title-buttons .order-status" ).wrap( "<h1></h1>" );
    jQuery(".Banner-logo, .Image-fixed, .Inner-Banner.Margin-top").remove();
</script>