<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="new-users half-box">
    <div class="content"> 
        <h3 id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__("Don't have an account")) ?></h3>
        <p class="form-instructions">Registration is free and easy!</p>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <ul class="benefits">
                <li><?= $block->escapeHtml(__('Faster checkout')) ?></li>
                <li><?= $block->escapeHtml(__('Save multiple shipping addresses')) ?></li>
                <li><?= $block->escapeHtml(__('View and track orders and more')) ?></li>
            </ul>
        </div>
    </div>
    <div class="buttons-set">
        <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create button btn"><?= $block->escapeHtml(__('Create an Account')) ?></a>
    </div>
</div>
<?php endif; ?>
</div>
