<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<?php /* ?><div class="page-title-wrapper<?= /* @escapeNotVerified  $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified  $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified  $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified  $title ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div><?php */ ?>

<section class="Inner-Banner Margin-top" style="height: 210px;">
<div class="Image-fixed"><img src="<?php echo $this->getViewFileUrl('images/Inner-Banner.jpg'); ?>" alt=""> </div>
 <div class="vertical-box">
  <div class="vertical-box-in">
   <div class="vertical-box-content">
    <div class="container">
     <div class="black-box">
      <h3 <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
      </h3>
       <?= $block->getChildHtml() ?>
     </div>
    </div>
   </div>
  </div>
 </div>
<?php /* ?><div class="myaccount_nav_warrper">
  <ul>
      <li> My Account </li>
      <li class="accountparent">
        <div class="accountchild">
            <?php echo $this->getLayout()->createBlock("Magento\Customer\Block\Account\Navigation")->setTemplate("Magento_Customer::account/navigation.phtml")->toHtml(); ?>
        </div>
      </li>
  </ul>
</div><?php */ ?>
</section>
<section class="Banner-logo"><img src="<?php echo $this->getViewFileUrl('images/Banner-logo.png'); ?>" alt="" class="common-logo"> </section>

<?php endif; ?>
